#ifndef DLLTIETOKANTA_GLOBAL_H
#define DLLTIETOKANTA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLTIETOKANTA_LIBRARY)
#  define DLLTIETOKANTASHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLTIETOKANTASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLTIETOKANTA_GLOBAL_H
