#ifndef DLLLAHJOITARAHAA_GLOBAL_H
#define DLLLAHJOITARAHAA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLLAHJOITARAHAA_LIBRARY)
#  define DLLLAHJOITARAHAASHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLLAHJOITARAHAASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLLAHJOITARAHAA_GLOBAL_H
