#ifndef DLLNOSTARAHAA_GLOBAL_H
#define DLLNOSTARAHAA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLNOSTARAHAA_LIBRARY)
#  define DLLNOSTARAHAASHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLNOSTARAHAASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLNOSTARAHAA_GLOBAL_H
