#ifndef DLLMAINMENU_GLOBAL_H
#define DLLMAINMENU_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLMAINMENU_LIBRARY)
#  define DLLMAINMENUSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLMAINMENUSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLMAINMENU_GLOBAL_H
