#ifndef DLLKIRJAUDUSISAAN_GLOBAL_H
#define DLLKIRJAUDUSISAAN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLKIRJAUDUSISAAN_LIBRARY)
#  define DLLKIRJAUDUSISAANSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLKIRJAUDUSISAANSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLKIRJAUDUSISAAN_GLOBAL_H
