#ifndef DLLRFLUKIJA_GLOBAL_H
#define DLLRFLUKIJA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLRFLUKIJA_LIBRARY)
#  define DLLRFLUKIJASHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLRFLUKIJASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLRFLUKIJA_GLOBAL_H
